export const GET_SHAMPOO_REQUEST="GET_SHAMPOO_REQUEST"
export const GET_SHAMPOO_SUCCESS="GET_SHAMPOO_SUCCESS"
export const GET_SHAMPOO_FAILURE="GET_SHAMPOO_FAILURE"

export const POST_SHAMPOO_REQUEST="POST_SHAMPOO_REQUEST"
export const POST_SHAMPOO_SUCCESS="POST_SHAMPOO_SUCCESS"
export const POST_SHAMPOO_FAILURE="POST_SHAMPOO_FAILURE"

export const PATCH_SHAMPOO_REQUEST="PATCH_SHAMPOO_REQUEST"
export const PATCH_SHAMPOO_SUCCESS="PATCH_SHAMPOO_SUCCESS"
export const PATCH_SHAMPOO_FAILURE="PATCH_SHAMPOO_FAILURE"

export const DELETE_SHAMPOO_REQUEST="DELETE_SHAMPOO_REQUEST"
export const DELETE_SHAMPOO_SUCCESS="DELETE_SHAMPOO_SUCCESS"
export const DELETE_SHAMPOO_FAILURE="DELETE_SHAMPOO_FAILURE"
