export const GET_FACE_WASH_REQUEST="GET_FACE_WASH_REQUEST"
export const GET_FACE_WASH_SUCCESS="GET_FACE_WASH_SUCCESS"
export const GET_FACE_WASH_FAILURE="GET_FACE_WASH_FAILURE"

export const POST_FACE_WASH_REQUEST="POST_FACE_WASH_REQUEST"
export const POST_FACE_WASH_SUCCESS="POST_FACE_WASH_SUCCESS"
export const POST_FACE_WASH_FAILURE="POST_FACE_WASH_FAILURE"

export const PATCH_FACE_WASH_REQUEST="PATCH_FACE_WASH_REQUEST"
export const PATCH_FACE_WASH_SUCCESS="PATCH_FACE_WASH_SUCCESS"
export const PATCH_FACE_WASH_FAILURE="PATCH_FACE_WASH_FAILURE"

export const DELETE_FACE_WASH_REQUEST="DELETE_FACE_WASH_REQUEST"
export const DELETE_FACE_WASH_SUCCESS="DELETE_FACE_WASH_REQUEST"
export const DELETE_FACE_WASH_FAILURE="DELETE_FACE_WASH_REQUEST"
