export const GET_PRIMER_REQUEST="GET_PRIMER_REQUEST"
export const GET_PRIMER_SUCCESS="GET_PRIMER_SUCCESS"
export const GET_PRIMER_FAILURE="GET_PRIMER_FAILURE"

export const POST_PRIMER_REQUEST="POST_PRIMER_REQUEST"
export const POST_PRIMER_SUCCESS="POST_PRIMER_SUCCESS"
export const POST_PRIMER_FAILURE="POST_PRIMER_FAILURE"

export const PATCH_PRIMER_REQUEST="PATCH_PRIMER_REQUEST"
export const PATCH_PRIMER_SUCCESS="PATCH_PRIMER_SUCCESS"
export const PATCH_PRIMER_FAILURE="PATCH_PRIMER_FAILURE"

export const DELETE_PRIMER_REQUEST="DELETE_PRIMER_REQUEST"
export const DELETE_PRIMER_SUCCESS="DELETE_PRIMER_SUCCESS"
export const DELETE_PRIMER_FAILURE="DELETE_PRIMER_FAILURE"
