export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"

export const PATCH_USER_REQUEST="PATCH_USER_REQUEST"
export const PATCH_USER_SUCCESS="PATCH_USER_SUCCESS"
export const PATCH_USER_FAILURE="PATCH_USER_FAILURE"