export const GET_USER_ORDER_REQUEST="GET_USER_ORDER_REQUEST"
export const GET_USER_ORDER_SUCCESS="GET_USER_ORDER_SUCCESS"
export const GET_USER_ORDER_FAILURE="GET_USER_ORDER_FAILURE"


export const GET_ALL_ORDER_REQUEST="GET_ALL_ORDER_REQUEST"
export const GET_ALL_ORDER_SUCCESS="GET_ALL_ORDER_SUCCESS"
export const GET_ALL_ORDER_FAILURE="GET_ALL_ORDER_FAILURE"

